---
all:
  hosts:
    master-01:
      ansible_user: zerobsv
      ansible_host: 192.168.111.111
      ansible_python_interpreter: /usr/bin/python3
    master-02:
      ansible_user: zerobsv
      ansible_host: 192.168.111.111
      ansible_python_interpreter: /usr/bin/python3
    worker-01:
      ansible_user: zerobsv
      ansible_host: 192.168.111.111
      ansible_python_interpreter: /usr/bin/python3
    worker-02:
      ansible_user: zerobsv
      ansible_host: 192.168.111.111
      ansible_python_interpreter: /usr/bin/python3
    loadbalancer-01:
      ansible_user: zerobsv
      ansible_host: 192.168.111.111
      ansible_python_interpreter: /usr/bin/python3

  children:
    loadbalancers:
      hosts:
        loadbalancer-01:

    first_master:
      hosts:
        master-01:

    other_masters:
      hosts:
        master-02:

    workers:
      hosts:
        worker-01:
        worker-02:

    k8s_masters:
      children:
        first_master:
        other_masters:
